

spring:
  security:
    oauth2:
      client:
        registration:
          #카카오
          kakao:
            client-id: ef05368d53b17421ea9e339d92a527a2
            client-secret: yUQ9ulkEYli0uzT8eYA2i4wqxBiuwTCn
            redirect-uri: http://localhost:9090/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
             - profile_nickname
             - profile_image
             - account_email
             - name
          #구글
          google:
             client-id: ${GOOGLE_CLIENT_ID}
             client-secret: ${GOOGLE_CLIENT_SECRET}
             scope:
               - openid                                                 # 1. openid
               - https://www.googleapis.com/auth/userinfo.email         # 2. 이메일
               - https://www.googleapis.com/auth/userinfo.profile       # 3. 프로필
           #네이버    
          naver:
             client-id: TNnf_gIETKAbyvGgU4YU
             client-secret: KUntZXQDw2
             scope:
               - name
               - email
               - profile
               - birthyear
               - birthday
               - mobile
             client-name: Naver
             authorization-grant-type: authorization_code
             redirect-uri: http://localhost:9090/login/oauth2/code/naver
        provider:
           kakao:
               authorization-uri: https://kauth.kakao.com/oauth/authorize
               token-uri: https://kauth.kakao.com/oauth/token
               user-info-uri: https://kapi.kakao.com/v2/user/me
               user-name-attribute: id
           naver:
               authorization-uri: https://nid.naver.com/oauth2.0/authorize
               token-uri: https://nid.naver.com/oauth2.0/token
               user-info-uri: https://openapi.naver.com/v1/nid/me
               user-name-attribute: response

#관리자 문의 메일 전송
  mail:
    host: smtp.gmail.com          # Gmail SMTP 서버 주소
    port: 587                     # SMTP 포트 (일반적으로 587)
    username: slswk159@gmail.com   # 발신자 Gmail 주소
    password: vzdmvjcxxgjdydzo         
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
